name: 'maestro-test-action'
description: 'Simple step to run Maestro tests with GitHub Actions'
author: 'dniHze'
inputs:
  flow:
    required: false
    description: 'Meastro flow or directory'
  report:
    required: false
    description: 'JUnit report destination'
    default: 'reports/maestro-test.xml'
  env:
    required: false
    description: 'environment variables'
    default: ''
  version:
    required: false
    description: 'Maestro CLI version'
    default: 'latest'
outputs:
  report:
    description: 'JUnit test report'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: purple
  icon: check-circle