name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  android-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: ./
        with:
          version: latest
      - run: |
          brew install tree
          tree /Users/runner/hostedtoolcache/maestro/1.17.4/x64
          tree /Users/runner/hostedtoolcache/idb-companion/1.1.8/x64
          echo $PATH
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          target: google_apis
          profile: Nexus 5
          script: maestro test --format=junit --output=reports/test.xml --no-ansi .maestro/android-contacts.yaml
