name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  android-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: ./
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          ram-size: 2048M
          target: default
          script: maestro test --format=junit --output=reports/test.xml --no-ansi .maestro/android-contacts.yaml
