name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  android-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: ./
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          ram-size: 2048M
          target: default
          script: maestro test --format=junit --output=report.xml --no-ansi .maestro/android-contacts.yaml
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: report
          path: report.xml
  ios-test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 14 Pro'
      - uses: ./
        with:
          flow: .maestro/ios-settings.yaml
          report: report.xml
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: report
          path: report.xml
